sous-chefs/rundeck

templates/default/profile.erb
When using an SSL terminated reverse proxy, users are redirected to a http:// URL during login. Jetty intercepts the request and does not respect the X-Forwarded-Proto header sent by the proxy. 
Add the workaround provided in https://github.com/rundeck/rundeck/issues/732
Support added in Rundeck in this commit: https://github.com/rundeck/rundeck/commit/f1cb0548fa3450f141247f68571dd8d70343c392
=> Fix https redirects when using a reverse proxy

templates/default/jaas-activedirectory.conf.erb
When working with my LDAP server, I use forcebindinglogin.  However, if I leave the bindDN and bindPassword with the default attributes set, it is still trying to bind with those creds instead of the user creds.  Just added an unless block to clean this up.
=> If forcebindinglogin is true, don't create the bind entries.

README.md, attributes/default.rb, templates/default/profile.erb, templates/default/rundeck.conf.erb
This is useful if the apache server is not dedicated to rundeck, so instead of http://hostname, we can use http://hostname/rundeck if you set webcontext = '/rundeck'.
=> Add option to use a webcontext other than '/'

README.md, attributes/default.rb, templates/default/framework.properties.erb
See the section about api tokens file here... http://rundeck.org/2.4.2/administration/configuration-file-reference.html#framework.properties
I have not added any method to create the tokens file itself yet, so that is still a manually process (or a template can be created in a wrapper cookbook).  I think we could just add the token field to the Rundeck Users data bag, and then create a new tokens.properties.erb file and populate it with tokens from the data bag.  I didn't want to get to deep into this though if that's not what you would prefer.
Thanks,
Matt
=> Support for api tokens_file - also fixed a couple typos

metadata.rb
When provisioning the rundeck::server recipe on rpm based systems, the following error is receieved:
No resource or method named `yum_repository' for `Chef::Recipe "server"'
This is fixed by adding the 'yum' cookbook as a dependency.
=> Fixes missing 'yum_repository' resource

recipes/server.rb
We are downloading the jar from a remote location (node['rundeck]['plugin']['slack']) and cookbook_file is searching for the file locally inside COOKBOOK/files/default directory causing chef run to fail.
=> Using remote_file instead of cookbook_file for installation of slack plugin

templates/default/framework.properties.erb
This will allow us to set the rundeck server URL and the rundeck URL with the FQDN of the rundeck server. Otherwise once we login to the web console it will redirect to http://localhost:4440 which will obviously not work.
=> Made some rundeck framework properties configurable.

templates/default/chef-rundeck.conf.erb
Restarting the process does not kill the child process, so new configuration are not loaded unless someone kills the child process manually.
Proposed change fixes the restarting issue.
=> Use 'exec' to substitute calling process instead of forking.

templates/default/chef-rundeck-systemd.conf.erb
On Debian 8 and thus systemd for chef-rundeck, I get the following error
```
[/etc/systemd/system/chef-rundeck.service:9] Executable path is not absolute, ignoring: "/opt/chef/embedded/bin/chef-rundeck -c /etc/chef/rundeck.rb -f /etc/chef/chef-rundeck....ndeck/server.log"
chef-rundeck.service lacks ExecStart setting. Refusing.
```
Dropping the quotes around the ExecStart command resolves it.
`rundeck systemd[1]: Started Chef Rundeck service.`
=> chef-rundeck systemd unit file syntax fix

README.md, attributes/default.rb, templates/default/rundeck-config.properties.erb
Quartz Job ThreadCounf is used to define the number of threads that rundeck will use to run parallel jobs. The default value is 10.
=> Added an attribute to configure Quartz job threadCount

attributes/default.rb
Adding a default property for Java 7 as this has been required in recent versions of rundeck.
See #87
=> Add default version property for jdk7

recipes/chef-rundeck.rb, recipes/chef_server_config.rb
Separating the logic of setting up chef environment will help use chef_server_config in other recipes. The primary reason is to use chef_server_config in chef_rundeck and better_chef_rundeck both.
=> Moved out chef environment setup logic from chef_rundeck to chef_server_config

recipes/server_install.rb
Simply better security, add the gpg key for the rpms and set the repo to verify the content.
=> RPMs are now signed, add key and verify.

libraries/rundeck_api_client.rb, spec/rundeck_api_client_spec.rb, test/integration/default/serverspec/localhost/rundeck_api_client_spec.rb
adds a wrapper around the constructor method and the authenticate method to get an authenticated api client
replaces #131
=> RundeckApiClient#connect to get an authenticated api client

attributes/default.rb, metadata.rb, recipes/_connect_rundeck_api_client.rb, spec/recipes/connect_api_client_spec.rb
this is for supporting older versions of build-essential cookbook that do not publish an lwrp
=> use build-essential default recipe rather than calling lwrp

libraries/rundeck_api_client.rb, metadata.rb, spec/libraries/rundeck_api_client_spec.rb
verify_ssl is the proper key to use with rest-client: https://github.com/rest-client/rest-client/blob/8874463a44ec6d5a702b7c9d4cc7c392bba80e0c/lib/restclient/request.rb#L99
when this was set in the initialization of the client it wasnt getting sent with every request
this should fix that
=> added failing spec for request_defaults merging

libraries/rundeck_api_client.rb, metadata.rb, spec/libraries/rundeck_api_client_spec.rb
this is unfortunately necessary so that keys passed in the request_defaults are symbols so that rest-client sees `:verify_ssl` rather than `'verify_ssl'`
=> symbolize all keys in config hash

spec/support/fixtures/data_bags/rundeck_projects, spec/support/fixtures/data_bags/rundeck_projects/localhost.json
There is currently a symlink of `spec/support/fixtures/data_bags/rundeck_projects` to `test/integration/default/data_bags/rundeck_projects`. This seemingly breaks using the cookbook in wrapper cookbooks as it causes Test Kitchen to error out.
I've replaced it with a single data bag item which fixes the issue and specs pass.
```
Transferring files to <rundeck-server-debian-88>
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-scp-1.2.1/lib/net/scp.rb:365:in `block (3 levels) in start_command': SCP did not finish successfully ():  (Net::SCP::Error)
```
```
Transferring files to <rundeck-server-debian-88>
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [No such file or directory @ …
```
=> Remove data bag symlink

metadata.rb
If you are using the Rundeck cookbook and the Java cookbook at the same time, you get `Chef::Exceptions::ProviderNotFound` when trying to use the `java_certificate` resource. This is because both the `java` and the `java-libraries` cookbook define a resource and provider with that name. 
As the `java-libraries` cookbook is now obsolete, removing it from the dependencies should have no effect.
=> Remove dependency on java-libraries

resources/server_install.rb
- Allow `private_key` to be nil and default to nil
- Enforce `private_key` as a sensitive resource
- Modify `only_if` to `not_if` and test for nil
Signed-off-by: Brian Menges <mengesb@gmail.com>
#203
=> Obvious fix - private_key

resources/server_install.rb
- Remove deprecated OpenJDK 8 option MaxPermSize
Signed-off-by: Brian Menges <mengesb@gmail.com>
#205
=> Remove deprecated OpenJDK 8 option MaxPermSize

resources/server_install.rb, templates/default/framework.properties.erb
Changes `tokensfile` to `tokens_file` as first one does not exist.
=> Change tokensfile var name in framework.properties template

CHANGELOG.md, documentation/resource_server_install.md, resources/server_install.rb
Added the missing option for ldap supplemental role. The active directory template file already had that option.
=> Added missing supplimental roles for LDAP users

.github/workflows/ci.yml, CHANGELOG.md, kitchen.dokken.yml, kitchen.yml, metadata.rb, resources/dependencies.rb
rundeck_dependencies was erroring because the java cookbook throws an error when trying to use recipes. Swapped out to the openjdk resource since that is supposed to be the default of the java cookbook.
=> Swap java recipe for resource
